### ISSUE TITLE
TypeError parsing Electron Release list

### ISSUE THREAD

**Issue by jason-invision** [doyensec/electronegativity#50]
**Describe the bug** 
During a scan of my app I receive a TypeError while the Electron Release List is being parsed.

**To Reproduce**
1. Run `electronegativity -i my-app -o results.csv`

**Expected behavior**
I expected the Release List to be parsed and my app to be scanned.

**Stacktraces **
```
Releases list is up to date.
(node:54021) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at run (/Users/jasonrogers/.nvm/versions/node/v8.15.1/lib/node_modules/@doyensec/electronegativity/dist/runner.js:211:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:54021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:54021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Platform (please complete the following information):**
 - OS: Mac
 - Electronegativity version: 1.2.1

**Additional context**
I noticed that downloading the Release List is taking a long time. Could the download be timing out, and, therefore, only a partial file being downloaded?

**Comment by phosphore** [comment]
Hey Jason,

Can you try cloning the Github repository? I think this should have been fixed in 84316b10ad081194a0f01a1b3cef70a21eefe92b, while the npm repo is still behind this.

Let me know if this fixes it or I'll investigate later in the day,

Cheers!

**Comment by jason-invision** [comment]
I cloned the Github repository and followed the build instructions with the same result.
```
git log --oneline | head -n 1
b32b81b report CSP sample in CSPGlobalCheck issues
```

**Comment by phosphore** [comment]
Hey @jason-invision,

Can you try to git pull the repository with the fix 69a4795f0a8ca396d73ea6e61e9df4652f33ad0f and let me know if that works for you?

Thanks!

**Comment by jason-invision** [comment]
I upgraded and am still receiving the same result. Is there something I can debug on my end to help identify the root cause?

**Comment by phosphore** [comment]
Sorry for the delay, 0b682c28881d4461261e390218a28bc13c1313bf should fix this. Try pulling the repository now and remember to run `npm run build`.

**Comment by jason-invision** [comment]
It appears to be working now. Thank you.
